--- !ditz.rubyforge.org,2008-03-06/project 
name: HsSVN
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: HsSVN
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: HsSVN-0.4.3.2
  status: :released
  release_time: 2011-07-28 06:29:04.755332 Z
  log_events: 
  - - 2011-07-28 06:04:46.388369 Z
    - PHO <pho@cielonegro.org>
    - created
    - Fix breakage on newer GHC and other libraries.
  - - 2011-07-28 06:29:04.755450 Z
    - PHO <pho@cielonegro.org>
    - released
    - Done.
